version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        # We use localhost:8000 because your BROWSER needs to talk to the backend
        - VITE_APP_BACKEND_URL_ARG=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always